//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MovieFavorites.Entities
{
    public partial class Movie
    {
        public int Id { get; set; }
        public string ImdbId { get; set; }
        public int TmdbId { get; set; }
        public string Title { get; set; }
        public string Teaser { get; set; }
        public int Year { get; set; }
        public string Backdrop { get; set; }
        public string Cover { get; set; }
    }
    
}
